blog:
    title: My blog
    url: http://www.myblog.com/
    description: This is my blog!

public_drafts: False
posts_in_homepage: 10
source_path: /Users/filippos/Desktop/blog_source
webroot: /Users/filippos/Desktop/croissant/html